# Generated by Django 4.0.8 on 2023-07-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0004_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='phonenumber',
            field=models.BigIntegerField(),
        ),
    ]
